-- ============================================================================
-- BluOnX Bid Management & Vendor Coordination System
-- Storage Bucket RLS Policies
-- ============================================================================
-- Version:  1.0
-- Date:     February 24, 2026
-- Author:   Awais Anwer (Tkrupt)
-- Depends:  Buckets must be created first via Supabase Dashboard
-- ============================================================================
--
-- PREREQUISITE:
--   Create these three PRIVATE buckets in the Supabase Dashboard → Storage
--   BEFORE running this script:
--     1. vendor-documents   (W-9, insurance certs, master trade agreements)
--     2. project-documents  (civil plans, drawings, specs, photos)
--     3. bid-attachments    (docs vendors upload with bid submissions)
--
-- ACCESS MODEL:
--   Authenticated users (admin/PM) → RLS policies below
--   Vendors (bid portal)           → FastAPI backend uses service_role key
--                                    (bypasses RLS entirely)
--   Anonymous / public             → no access (no anon policies)
--
-- FILE PATH CONVENTIONS (stored in DB file_path columns):
--   vendor-documents:  {vendor_id}/{document_type}/{filename}
--   project-documents: {project_id}/{filename}
--   bid-attachments:   {bid_submission_id}/{filename}
--
-- ============================================================================


-- ────────────────────────────────────────────────────────────────────────────
-- VENDOR-DOCUMENTS BUCKET
-- W-9, Insurance Certificates, Master Trade Agreements
-- ────────────────────────────────────────────────────────────────────────────

CREATE POLICY "auth users can read vendor-documents"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'vendor-documents' );

CREATE POLICY "auth users can upload vendor-documents"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'vendor-documents' );

CREATE POLICY "auth users can update vendor-documents"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'vendor-documents' );

CREATE POLICY "auth users can delete vendor-documents"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'vendor-documents' );


-- ────────────────────────────────────────────────────────────────────────────
-- PROJECT-DOCUMENTS BUCKET
-- Civil plans, drawings, specs, site photos
-- Vendors access these via signed URLs generated by the backend.
-- ────────────────────────────────────────────────────────────────────────────

CREATE POLICY "auth users can read project-documents"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'project-documents' );

CREATE POLICY "auth users can upload project-documents"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'project-documents' );

CREATE POLICY "auth users can update project-documents"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'project-documents' );

CREATE POLICY "auth users can delete project-documents"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'project-documents' );


-- ────────────────────────────────────────────────────────────────────────────
-- BID-ATTACHMENTS BUCKET
-- Documents vendors submit with their bids (updated W-9, signed SOW, etc.)
-- Vendor uploads handled by FastAPI (service_role key — bypasses RLS).
-- PMs view from dashboard (authenticated).
-- ────────────────────────────────────────────────────────────────────────────

CREATE POLICY "auth users can read bid-attachments"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'bid-attachments' );

CREATE POLICY "auth users can upload bid-attachments"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'bid-attachments' );

CREATE POLICY "auth users can update bid-attachments"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'bid-attachments' );

CREATE POLICY "auth users can delete bid-attachments"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'bid-attachments' );


-- ============================================================================
-- VERIFICATION
-- ============================================================================
-- Run after applying to confirm 12 policies exist:
--
-- SELECT policyname, cmd
--   FROM pg_policies
--  WHERE schemaname = 'storage'
--    AND tablename = 'objects'
--  ORDER BY policyname;
--
-- ============================================================================
-- END OF STORAGE RLS POLICIES
-- ============================================================================
-- Summary:
--   Buckets:           3 (all private)
--   Policies:         12 (4 operations × 3 buckets)
--   Authenticated:    Full CRUD on all buckets
--   Anonymous:        ZERO access
--   Vendor access:    Via FastAPI service_role (bypasses RLS)
-- ============================================================================
