-- ============================================================================
-- BluOnX Bid Management & Vendor Coordination System
-- Storage Bucket RLS Policies
-- ============================================================================
-- Version:  1.1
-- Date:     September 9, 2026
-- Author:   Awais Anwer (Tkrupt)
-- Depends:  Buckets must exist first (created empty via Supabase Dashboard)
-- ============================================================================
--
-- PREREQUISITE:
--   Create these three PRIVATE buckets in the Supabase Dashboard → Storage
--   BEFORE running this script. Create them with the DEFAULT settings: leave
--   the "Allowed MIME types" field and the file size limit alone. This script
--   configures both (see BUCKET CONFIGURATION below); setting them by hand in
--   the Dashboard is what let the bucket config drift out of step with the
--   application's allow-list.
--     1. vendor-documents   (W-9, insurance certs, master trade agreements)
--     2. project-documents  (civil plans, drawings, specs, photos)
--     3. bid-attachments    (docs vendors upload with bid submissions)
--
-- ACCESS MODEL:
--   Authenticated users (admin/PM) → RLS policies below
--   Vendors (bid portal)           → FastAPI backend uses service_role key
--                                    (bypasses RLS entirely)
--   Anonymous / public             → no access (no anon policies)
--
-- FILE PATH CONVENTIONS (stored in DB file_path columns):
--   vendor-documents:  {vendor_id}/{document_type}/{filename}
--   project-documents: {project_id}/{filename}
--   bid-attachments:   {bid_submission_id}/{filename}
--
-- ============================================================================


-- ────────────────────────────────────────────────────────────────────────────
-- BUCKET CONFIGURATION
-- Runs after bucket creation, before the policies. Idempotent, safe to re-run.
--
-- allowed_mime_types is deliberately NULL: there is NO bucket-level MIME
-- enforcement. MIME/extension validation lives in the application layer, in
-- BUCKET_CONFIGS[...]["allowed_extensions"] in
-- backend/app/core/file_validation.py, which is the single gate. Uploads are
-- extension-first because CAD (.dwg/.dxf/.dwf/.dgn) and some Office files
-- arrive as application/octet-stream, and a bucket-level MIME list cannot
-- express that. When such a list drifted narrower than the app's allow-list, DOCX /
-- XLSX / CAD uploads passed app validation and then failed at storage as an
-- opaque 500. Do not reintroduce it.
--
-- DEV (Supabase free tier: 50 MB is a hard cap on that tier):
-- ────────────────────────────────────────────────────────────────────────────

UPDATE storage.buckets
   SET allowed_mime_types = NULL,
       file_size_limit    = 52428800          -- 50 MB
 WHERE id IN ('vendor-documents', 'project-documents');

UPDATE storage.buckets
   SET allowed_mime_types = NULL,
       file_size_limit    = 10485760          -- 10 MB, matches
                                              -- MAX_ATTACHMENT_BYTES in
                                              -- backend/app/routers/vendor_portal.py
 WHERE id = 'bid-attachments';

-- PRODUCTION (Pro plan): raise the global limit in Storage → Settings first,
-- then run these two INSTEAD OF the pair above. bid-attachments stays at 10 MB
-- in every environment, because that is a product rule, not a plan limit.
--
--   UPDATE storage.buckets
--      SET allowed_mime_types = NULL,
--          file_size_limit    = 209715200    -- 200 MB
--    WHERE id IN ('vendor-documents', 'project-documents');
--
--   UPDATE storage.buckets
--      SET allowed_mime_types = NULL,
--          file_size_limit    = 10485760     -- 10 MB
--    WHERE id = 'bid-attachments';

-- ────────────────────────────────────────────────────────────────────────────
-- VENDOR-DOCUMENTS BUCKET
-- W-9, Insurance Certificates, Master Trade Agreements
-- ────────────────────────────────────────────────────────────────────────────

CREATE POLICY "auth users can read vendor-documents"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'vendor-documents' );

CREATE POLICY "auth users can upload vendor-documents"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'vendor-documents' );

CREATE POLICY "auth users can update vendor-documents"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'vendor-documents' );

CREATE POLICY "auth users can delete vendor-documents"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'vendor-documents' );


-- ────────────────────────────────────────────────────────────────────────────
-- PROJECT-DOCUMENTS BUCKET
-- Civil plans, drawings, specs, site photos
-- Vendors access these via signed URLs generated by the backend.
-- ────────────────────────────────────────────────────────────────────────────

CREATE POLICY "auth users can read project-documents"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'project-documents' );

CREATE POLICY "auth users can upload project-documents"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'project-documents' );

CREATE POLICY "auth users can update project-documents"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'project-documents' );

CREATE POLICY "auth users can delete project-documents"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'project-documents' );


-- ────────────────────────────────────────────────────────────────────────────
-- BID-ATTACHMENTS BUCKET
-- Documents vendors submit with their bids (updated W-9, signed SOW, etc.)
-- Vendor uploads handled by FastAPI (service_role key — bypasses RLS).
-- PMs view from dashboard (authenticated).
-- ────────────────────────────────────────────────────────────────────────────

CREATE POLICY "auth users can read bid-attachments"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'bid-attachments' );

CREATE POLICY "auth users can upload bid-attachments"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'bid-attachments' );

CREATE POLICY "auth users can update bid-attachments"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'bid-attachments' );

CREATE POLICY "auth users can delete bid-attachments"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'bid-attachments' );


-- ============================================================================
-- VERIFICATION
-- ============================================================================
-- Run after applying to confirm 12 policies exist:
--
-- SELECT policyname, cmd
--   FROM pg_policies
--  WHERE schemaname = 'storage'
--    AND tablename = 'objects'
--  ORDER BY policyname;
--
-- And to confirm the bucket configuration applied:
--
-- SELECT id, file_size_limit, allowed_mime_types
--   FROM storage.buckets
--  WHERE id IN ('vendor-documents','project-documents','bid-attachments');
--
-- Expect allowed_mime_types NULL on all three.
--
-- ============================================================================
-- END OF STORAGE RLS POLICIES
-- ============================================================================
-- Summary:
--   Buckets:           3 (all private, MIME list NULL by design)
--   Policies:         12 (4 operations × 3 buckets)
--   Authenticated:    Full CRUD on all buckets
--   Anonymous:        ZERO access
--   Vendor access:    Via FastAPI service_role (bypasses RLS)
-- ============================================================================
